import type { NextPage } from 'next'
import Head from 'next/head'
import Banner from '../components/Home/Banner'
import TrendingSection from '../components/Home/Trending-Invenstments/FindProjectSection'
import FeaturedProperty from '../components/Home/Featured-Products/FeaturedProperty'
import TopProperties from '../components/Home/TopProperties'
import InvestContent from '../components/Home/InvestContent'
import InvestorAndDeveloper from '../components/Home/InvestorAndDeveloper'

const Home: NextPage = ({data}: any) => {
    return (
        <>
            <Head>
                <title>Handover Digital Holdings FZCO</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <Banner />
            
            <TopProperties properties={data.latest_properties} />

            <TrendingSection />

            <InvestorAndDeveloper />

            <InvestContent />
            
            { data.latest_properties != null && <FeaturedProperty data={data.latest_properties} /> }
            
            {/* <BlogSection /> */}
        </>
    )
}

export default Home

export async function getServerSideProps(context: any) {
    // Fetch data from external API
    let latest_properties = null;
    const res = await fetch(`${process.env.API_URL}/property/sort/desc`)
    if(res.status==200)
    {
        latest_properties = await res.json()
    }
  
    // Pass data to the page via props
    return { 
        props: { 
            data: {
                latest_properties
            }
        }
    }
}